export const mockActivity = {
  count: 10,
  status: 'success',
  data: [
    {
      body: '',
      caption: 'complete bungalow',
      post_id: '54',
      shared: '0',
      type: 'product',
      likes: '-1',
      address: 'Abuja, nigeria,  sierria leone, Ghana',
      date_created: '1558979386',
      event_type: '',
      comments: '0',
      post_user_id: '9',
      full_name: 'Rita Ora',
      username: 'ritaForYou',
      profile_thumb: 'uploads/profile/thumb/5ccaf40405e41-1556804612.jpg',
      path: 'uploads/post/photo/13.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: 'rent',
      product_category: 'service',
      product_price: '390000',
      product_name: 'complete bungalow in lugbe federal housing estate',
      product_id: '8'
    },
    {
      body: '',
      caption: '250GHz Complete Stage Light Set',
      post_id: '51',
      shared: '0',
      type: 'product',
      likes: '-1',
      address: 'Abuja, nigeria,  sierria leone, Ghana',
      date_created: '1558976723',
      event_type: '',
      comments: '0',
      post_user_id: '4',
      full_name: 'jerry springer',
      username: 'hitMan',
      profile_thumb: '',
      path: 'uploads/post/photo/10.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: 'sell',
      product_category: 'product',
      product_price: '5350000',
      product_name: '250GHz Complete Stage Light Set',
      product_id: '5'
    },
    {
      body: '',
      caption: 'Nikon camera stand 590k resolution',
      post_id: '49',
      shared: '0',
      type: 'product',
      likes: '0',
      address: 'Abuja, nigeria,  sierria leone, Ghana',
      date_created: '1558979146',
      event_type: '',
      comments: '0',
      post_user_id: '4',
      full_name: 'jerry springer',
      username: 'hitMan',
      profile_thumb: '',
      path: 'uploads/post/photo/19.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: 'sell',
      product_category: 'product',
      product_price: '950000',
      product_name: 'Nickon tripod camera stand 590k resolution',
      product_id: '3'
    },
    {
      body: '',
      caption: 'cannon camera 290k resolution',
      post_id: '47',
      shared: '0',
      type: 'product',
      likes: '0',
      address: 'Abuja, nigeria,  sierria leone, Ghana',
      date_created: '1558976723',
      event_type: '',
      comments: '0',
      post_user_id: '2',
      full_name: 'andrew',
      username: 'guyFly',
      profile_thumb: 'uploads/profile/thumb/thumb-98.jpg',
      path: 'uploads/post/photo/15.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: 'sell',
      product_category: 'product',
      product_price: '2500000',
      product_name: 'cannon camera 290k resolution',
      product_id: '1'
    },
    {
      body: 'well this is a test',
      caption: 'well test',
      post_id: '46',
      shared: '0',
      type: 'photo',
      likes: '8972',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '1',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/13.jpg',
      like_status: '1',
      dislike_status: '0',
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'well this is a test',
      caption: 'well test',
      post_id: '45',
      shared: '0',
      type: 'photo',
      likes: '8978',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/12.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'well this is a test',
      caption: 'well test',
      post_id: '44',
      shared: '0',
      type: 'photo',
      likes: '8977',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/11.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'well this is a test',
      caption: 'well test',
      post_id: '43',
      shared: '0',
      type: 'photo',
      likes: '8976',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/10.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'well this is a test',
      caption: 'well test',
      post_id: '42',
      shared: '0',
      type: 'photo',
      likes: '8976',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/18.jpg',
      like_status: '1',
      dislike_status: '0',
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'well this is a test',
      caption: 'well test',
      post_id: '41',
      shared: '0',
      type: 'photo',
      likes: '8977',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/19.jpg',
      like_status: '1',
      dislike_status: '0',
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'well this is a test',
      caption: 'well test',
      post_id: '40',
      shared: '0',
      type: 'photo',
      likes: '8975',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/14.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'well this is a test',
      caption: 'well test',
      post_id: '39',
      shared: '0',
      type: 'photo',
      likes: '8975',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/15.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'well this is a test',
      caption: 'well test',
      post_id: '38',
      shared: '0',
      type: 'photo',
      likes: '8975',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/16.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'well this is a test',
      caption: 'well test',
      post_id: '37',
      shared: '0',
      type: 'photo',
      likes: '8975',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/17.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'well this is a test',
      caption: 'well test',
      post_id: '36',
      shared: '0',
      type: 'photo',
      likes: '8975',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/18.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'well this is a test',
      caption: 'well test',
      post_id: '35',
      shared: '0',
      type: 'photo',
      likes: '8975',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/19.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'well this is a test',
      caption: 'well test',
      post_id: '34',
      shared: '0',
      type: 'photo',
      likes: '8975',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/20.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: '',
      caption: 'Why cant the title be blanl ?',
      post_id: '33',
      shared: '0',
      type: 'casting-call',
      likes: '0',
      address: 'Abuja, nigeria,  sierria leone, Ghana',
      date_created: '1558979467',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: null,
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: '',
      caption: 'A title A clohsjk',
      post_id: '32',
      shared: '0',
      type: 'casting-call',
      likes: '0',
      address: 'Abuja, nigeria,  sierria leone, Ghana',
      date_created: '1558979386',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: null,
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: '',
      caption: 'Title',
      post_id: '31',
      shared: '0',
      type: 'casting-call',
      likes: '0',
      address: 'Abuja, nigeria,  sierria leone, Ghana',
      date_created: '1558979146',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: null,
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: '',
      caption: 'Title',
      post_id: '29',
      shared: '0',
      type: 'casting-call',
      likes: '0',
      address: 'Abuja, nigeria,  sierria leone, Ghana',
      date_created: '1558976844',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/video/5cdbfea85295e-1557921448.mp4',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: '',
      caption: 'Title',
      post_id: '28',
      shared: '0',
      type: 'casting-call',
      likes: '0',
      address: 'Abuja, nigeria,  sierria leone, Ghana',
      date_created: '1558976723',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/5cdaed14bfecb-1557851412.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'assddd #',
      caption: '',
      post_id: '27',
      shared: '0',
      type: 'video',
      likes: '30',
      address: 'Sudan Street, Boulaq Ad Dakrour, Ad Doqi, Egypt',
      date_created: '1557246895',
      event_type: '',
      comments: '21',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/video/4873.mp4',
      like_status: '1',
      dislike_status: '0',
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'assddd #',
      caption: '',
      post_id: '26',
      shared: '0',
      type: 'event',
      likes: '0',
      address: 'Sudan Street, Boulaq Ad Dakrour, Ad Doqi, Egypt',
      date_created: '1557246895',
      event_type: 'concert',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: null,
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'assddd #',
      caption: '',
      post_id: '25',
      shared: '0',
      type: 'event',
      likes: '46',
      address: 'Sudan Street, Boulaq Ad Dakrour, Ad Doqi, Egypt',
      date_created: '1557246895',
      event_type: 'party',
      comments: '53',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: null,
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'assddd #',
      caption: '',
      post_id: '24',
      shared: '0',
      type: 'event',
      likes: '0',
      address: 'Sudan Street, Boulaq Ad Dakrour, Ad Doqi, Egypt',
      date_created: '1557246895',
      event_type: 'drama',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/3.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'assddd #',
      caption: '',
      post_id: '23',
      shared: '0',
      type: 'event',
      likes: '35',
      address: 'Sudan Street, Boulaq Ad Dakrour, Ad Doqi, Egypt',
      date_created: '1557246895',
      event_type: 'show',
      comments: '27',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/2.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body:
        'Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test',
      caption: '',
      post_id: '11',
      shared: '0',
      type: 'text',
      likes: '0',
      address: 'jsajksklsls;ls;;a;a;;a;jjjdjd',
      date_created: '1556978347',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: null,
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'also there is a Love is indeed Truth is well this is a test',
      caption: '',
      post_id: '10',
      shared: '0',
      type: 'text',
      likes: '312',
      address: 'jsajksklsls;ls;;a;a;;a;jjjdjd',
      date_created: '1556977643',
      event_type: '',
      comments: '23',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: null,
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body:
        'Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test Love is indeed Truth is well this is a test',
      caption: 'Love is a great gift Truth is well test',
      post_id: '6',
      shared: '0',
      type: 'photo',
      likes: '3892',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '16',
      post_user_id: '14',
      full_name: 'Solomon John',
      username: 'garriSon_01',
      profile_thumb: 'uploads/profile/thumb/5ccaf40405e41-1556804612.jpg',
      path: 'uploads/post/photo/1.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'Truth is well this is a test',
      caption: 'Truth is well test',
      post_id: '5',
      shared: '0',
      type: 'video',
      likes: '6745',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '0',
      post_user_id: '4',
      full_name: 'jerry springer',
      username: 'hitMan',
      profile_thumb: '',
      path: 'uploads/post/video/4872.mp4',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'you can this is a test',
      caption: 'you can test',
      post_id: '3',
      shared: '0',
      type: 'text',
      likes: '19',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '20',
      post_user_id: '9',
      full_name: 'Rita Ora',
      username: 'ritaForYou',
      profile_thumb: 'uploads/profile/thumb/5ccaf40405e41-1556804612.jpg',
      path: null,
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'well this is a test',
      caption: 'well test',
      post_id: '2',
      shared: '0',
      type: 'photo',
      likes: '8976',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: 'uploads/post/photo/1.jpg',
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'this is a test',
      caption: 'test',
      post_id: '1',
      shared: '0',
      type: 'text',
      likes: '30',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '121',
      post_user_id: '2',
      full_name: 'andrew',
      username: 'guyFly',
      profile_thumb: 'uploads/profile/thumb/thumb-98.jpg',
      path: null,
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    },
    {
      body: 'you will think Love is indeed Truth is well this is a test',
      caption: '',
      post_id: '7',
      shared: '0',
      type: 'product',
      likes: '0',
      address: '',
      date_created: '0',
      event_type: '',
      comments: '0',
      post_user_id: '3',
      full_name: 'Alhaji Bakure ',
      username: 'Drew007',
      profile_thumb: 'uploads/profile/thumb/g.jpg',
      path: null,
      like_status: null,
      dislike_status: null,
      shared_body: null,
      shared_type: null,
      shared_shared: null,
      product_purpose: null,
      product_category: null,
      product_price: null,
      product_name: null,
      product_id: null
    }
  ]
};
